/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R403RouteImport } from './routes/403'
import { Route as R405RouteImport } from './routes/405'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RemindersRouteImport } from './routes/reminders'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as AddExpenseRouteImport } from './routes/add.expense'
import { Route as AddFuelRouteImport } from './routes/add.fuel'
import { Route as AddOdometerRouteImport } from './routes/add.odometer'
import { Route as AddServiceRouteImport } from './routes/add.service'
import { Route as GloveboxIndexRouteImport } from './routes/glovebox.index'
import { Route as GloveboxDocIdRouteImport } from './routes/glovebox.$docId'
import { Route as GloveboxNewRouteImport } from './routes/glovebox.new'
import { Route as VehicleIndexRouteImport } from './routes/vehicle.index'
import { Route as VehicleVehicleIdRouteImport } from './routes/vehicle.$vehicleId'
import { Route as VehicleNewRouteImport } from './routes/vehicle.new'
import { Route as GloveboxDocIdEditRouteImport } from './routes/glovebox.$docId.edit'
import { Route as VehicleVehicleIdEditRouteImport } from './routes/vehicle_.$vehicleId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const R405Route = R405RouteImport.update({
  id: '/405',
  path: '/405',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersRoute = RemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const AddExpenseRoute = AddExpenseRouteImport.update({
  id: '/add/expense',
  path: '/add/expense',
  getParentRoute: () => rootRouteImport,
} as any)
const AddFuelRoute = AddFuelRouteImport.update({
  id: '/add/fuel',
  path: '/add/fuel',
  getParentRoute: () => rootRouteImport,
} as any)
const AddOdometerRoute = AddOdometerRouteImport.update({
  id: '/add/odometer',
  path: '/add/odometer',
  getParentRoute: () => rootRouteImport,
} as any)
const AddServiceRoute = AddServiceRouteImport.update({
  id: '/add/service',
  path: '/add/service',
  getParentRoute: () => rootRouteImport,
} as any)
const GloveboxIndexRoute = GloveboxIndexRouteImport.update({
  id: '/glovebox/',
  path: '/glovebox/',
  getParentRoute: () => rootRouteImport,
} as any)
const GloveboxDocIdRoute = GloveboxDocIdRouteImport.update({
  id: '/glovebox/$docId',
  path: '/glovebox/$docId',
  getParentRoute: () => rootRouteImport,
} as any)
const GloveboxNewRoute = GloveboxNewRouteImport.update({
  id: '/glovebox/new',
  path: '/glovebox/new',
  getParentRoute: () => rootRouteImport,
} as any)
const VehicleIndexRoute = VehicleIndexRouteImport.update({
  id: '/vehicle/',
  path: '/vehicle/',
  getParentRoute: () => rootRouteImport,
} as any)
const VehicleVehicleIdRoute = VehicleVehicleIdRouteImport.update({
  id: '/vehicle/$vehicleId',
  path: '/vehicle/$vehicleId',
  getParentRoute: () => rootRouteImport,
} as any)
const VehicleNewRoute = VehicleNewRouteImport.update({
  id: '/vehicle/new',
  path: '/vehicle/new',
  getParentRoute: () => rootRouteImport,
} as any)
const GloveboxDocIdEditRoute = GloveboxDocIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => GloveboxDocIdRoute,
} as any)
const VehicleVehicleIdEditRoute = VehicleVehicleIdEditRouteImport.update({
  id: '/vehicle_/$vehicleId/edit',
  path: '/vehicle/$vehicleId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/405': typeof R405Route
  '/insights': typeof InsightsRoute
  '/maintenance': typeof MaintenanceRoute
  '/privacy': typeof PrivacyRoute
  '/reminders': typeof RemindersRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/timeline': typeof TimelineRoute
  '/welcome': typeof WelcomeRoute
  '/add/expense': typeof AddExpenseRoute
  '/add/fuel': typeof AddFuelRoute
  '/add/odometer': typeof AddOdometerRoute
  '/add/service': typeof AddServiceRoute
  '/glovebox/$docId': typeof GloveboxDocIdRouteWithChildren
  '/glovebox/new': typeof GloveboxNewRoute
  '/vehicle/$vehicleId': typeof VehicleVehicleIdRoute
  '/vehicle/new': typeof VehicleNewRoute
  '/glovebox/': typeof GloveboxIndexRoute
  '/vehicle/': typeof VehicleIndexRoute
  '/glovebox/$docId/edit': typeof GloveboxDocIdEditRoute
  '/vehicle/$vehicleId/edit': typeof VehicleVehicleIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/405': typeof R405Route
  '/insights': typeof InsightsRoute
  '/maintenance': typeof MaintenanceRoute
  '/privacy': typeof PrivacyRoute
  '/reminders': typeof RemindersRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/timeline': typeof TimelineRoute
  '/welcome': typeof WelcomeRoute
  '/add/expense': typeof AddExpenseRoute
  '/add/fuel': typeof AddFuelRoute
  '/add/odometer': typeof AddOdometerRoute
  '/add/service': typeof AddServiceRoute
  '/glovebox/$docId': typeof GloveboxDocIdRouteWithChildren
  '/glovebox/new': typeof GloveboxNewRoute
  '/vehicle/$vehicleId': typeof VehicleVehicleIdRoute
  '/vehicle/new': typeof VehicleNewRoute
  '/glovebox': typeof GloveboxIndexRoute
  '/vehicle': typeof VehicleIndexRoute
  '/glovebox/$docId/edit': typeof GloveboxDocIdEditRoute
  '/vehicle/$vehicleId/edit': typeof VehicleVehicleIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/405': typeof R405Route
  '/insights': typeof InsightsRoute
  '/maintenance': typeof MaintenanceRoute
  '/privacy': typeof PrivacyRoute
  '/reminders': typeof RemindersRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/timeline': typeof TimelineRoute
  '/welcome': typeof WelcomeRoute
  '/add/expense': typeof AddExpenseRoute
  '/add/fuel': typeof AddFuelRoute
  '/add/odometer': typeof AddOdometerRoute
  '/add/service': typeof AddServiceRoute
  '/glovebox/$docId': typeof GloveboxDocIdRouteWithChildren
  '/glovebox/new': typeof GloveboxNewRoute
  '/vehicle/$vehicleId': typeof VehicleVehicleIdRoute
  '/vehicle/new': typeof VehicleNewRoute
  '/glovebox/': typeof GloveboxIndexRoute
  '/vehicle/': typeof VehicleIndexRoute
  '/glovebox/$docId/edit': typeof GloveboxDocIdEditRoute
  '/vehicle_/$vehicleId/edit': typeof VehicleVehicleIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/403'
    | '/405'
    | '/insights'
    | '/maintenance'
    | '/privacy'
    | '/reminders'
    | '/search'
    | '/settings'
    | '/timeline'
    | '/welcome'
    | '/add/expense'
    | '/add/fuel'
    | '/add/odometer'
    | '/add/service'
    | '/glovebox/$docId'
    | '/glovebox/new'
    | '/vehicle/$vehicleId'
    | '/vehicle/new'
    | '/glovebox/'
    | '/vehicle/'
    | '/glovebox/$docId/edit'
    | '/vehicle/$vehicleId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/403'
    | '/405'
    | '/insights'
    | '/maintenance'
    | '/privacy'
    | '/reminders'
    | '/search'
    | '/settings'
    | '/timeline'
    | '/welcome'
    | '/add/expense'
    | '/add/fuel'
    | '/add/odometer'
    | '/add/service'
    | '/glovebox/$docId'
    | '/glovebox/new'
    | '/vehicle/$vehicleId'
    | '/vehicle/new'
    | '/glovebox'
    | '/vehicle'
    | '/glovebox/$docId/edit'
    | '/vehicle/$vehicleId/edit'
  id:
    | '__root__'
    | '/'
    | '/403'
    | '/405'
    | '/insights'
    | '/maintenance'
    | '/privacy'
    | '/reminders'
    | '/search'
    | '/settings'
    | '/timeline'
    | '/welcome'
    | '/add/expense'
    | '/add/fuel'
    | '/add/odometer'
    | '/add/service'
    | '/glovebox/$docId'
    | '/glovebox/new'
    | '/vehicle/$vehicleId'
    | '/vehicle/new'
    | '/glovebox/'
    | '/vehicle/'
    | '/glovebox/$docId/edit'
    | '/vehicle_/$vehicleId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R403Route: typeof R403Route
  R405Route: typeof R405Route
  InsightsRoute: typeof InsightsRoute
  MaintenanceRoute: typeof MaintenanceRoute
  PrivacyRoute: typeof PrivacyRoute
  RemindersRoute: typeof RemindersRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  TimelineRoute: typeof TimelineRoute
  WelcomeRoute: typeof WelcomeRoute
  AddExpenseRoute: typeof AddExpenseRoute
  AddFuelRoute: typeof AddFuelRoute
  AddOdometerRoute: typeof AddOdometerRoute
  AddServiceRoute: typeof AddServiceRoute
  GloveboxDocIdRoute: typeof GloveboxDocIdRouteWithChildren
  GloveboxNewRoute: typeof GloveboxNewRoute
  VehicleVehicleIdRoute: typeof VehicleVehicleIdRoute
  VehicleNewRoute: typeof VehicleNewRoute
  GloveboxIndexRoute: typeof GloveboxIndexRoute
  VehicleIndexRoute: typeof VehicleIndexRoute
  VehicleVehicleIdEditRoute: typeof VehicleVehicleIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/405': {
      id: '/405'
      path: '/405'
      fullPath: '/405'
      preLoaderRoute: typeof R405RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders': {
      id: '/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof RemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add/expense': {
      id: '/add/expense'
      path: '/add/expense'
      fullPath: '/add/expense'
      preLoaderRoute: typeof AddExpenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add/fuel': {
      id: '/add/fuel'
      path: '/add/fuel'
      fullPath: '/add/fuel'
      preLoaderRoute: typeof AddFuelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add/odometer': {
      id: '/add/odometer'
      path: '/add/odometer'
      fullPath: '/add/odometer'
      preLoaderRoute: typeof AddOdometerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add/service': {
      id: '/add/service'
      path: '/add/service'
      fullPath: '/add/service'
      preLoaderRoute: typeof AddServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glovebox/': {
      id: '/glovebox/'
      path: '/glovebox'
      fullPath: '/glovebox/'
      preLoaderRoute: typeof GloveboxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glovebox/$docId': {
      id: '/glovebox/$docId'
      path: '/glovebox/$docId'
      fullPath: '/glovebox/$docId'
      preLoaderRoute: typeof GloveboxDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glovebox/new': {
      id: '/glovebox/new'
      path: '/glovebox/new'
      fullPath: '/glovebox/new'
      preLoaderRoute: typeof GloveboxNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicle/': {
      id: '/vehicle/'
      path: '/vehicle'
      fullPath: '/vehicle/'
      preLoaderRoute: typeof VehicleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicle/$vehicleId': {
      id: '/vehicle/$vehicleId'
      path: '/vehicle/$vehicleId'
      fullPath: '/vehicle/$vehicleId'
      preLoaderRoute: typeof VehicleVehicleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicle/new': {
      id: '/vehicle/new'
      path: '/vehicle/new'
      fullPath: '/vehicle/new'
      preLoaderRoute: typeof VehicleNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glovebox/$docId/edit': {
      id: '/glovebox/$docId/edit'
      path: '/edit'
      fullPath: '/glovebox/$docId/edit'
      preLoaderRoute: typeof GloveboxDocIdEditRouteImport
      parentRoute: typeof GloveboxDocIdRoute
    }
    '/vehicle_/$vehicleId/edit': {
      id: '/vehicle_/$vehicleId/edit'
      path: '/vehicle/$vehicleId/edit'
      fullPath: '/vehicle/$vehicleId/edit'
      preLoaderRoute: typeof VehicleVehicleIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GloveboxDocIdRouteChildren {
  GloveboxDocIdEditRoute: typeof GloveboxDocIdEditRoute
}

const GloveboxDocIdRouteChildren: GloveboxDocIdRouteChildren = {
  GloveboxDocIdEditRoute: GloveboxDocIdEditRoute,
}

const GloveboxDocIdRouteWithChildren = GloveboxDocIdRoute._addFileChildren(
  GloveboxDocIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R403Route: R403Route,
  R405Route: R405Route,
  InsightsRoute: InsightsRoute,
  MaintenanceRoute: MaintenanceRoute,
  PrivacyRoute: PrivacyRoute,
  RemindersRoute: RemindersRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  TimelineRoute: TimelineRoute,
  WelcomeRoute: WelcomeRoute,
  AddExpenseRoute: AddExpenseRoute,
  AddFuelRoute: AddFuelRoute,
  AddOdometerRoute: AddOdometerRoute,
  AddServiceRoute: AddServiceRoute,
  GloveboxDocIdRoute: GloveboxDocIdRouteWithChildren,
  GloveboxNewRoute: GloveboxNewRoute,
  VehicleVehicleIdRoute: VehicleVehicleIdRoute,
  VehicleNewRoute: VehicleNewRoute,
  GloveboxIndexRoute: GloveboxIndexRoute,
  VehicleIndexRoute: VehicleIndexRoute,
  VehicleVehicleIdEditRoute: VehicleVehicleIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
